---
title: 'Research: Using linear mixed-effects model to detect fraudulent erasures at an aggregate level'
author: ''
date: '2019-03-10'
slug: using-linear-mixed-effects-model-to-detect-fraudulent-erasures-at-an-aggregate-level
categories:
  - My Research
tags:
  - Mixed-effects Model
---

Abstract

Wollack and Eckerly (2017) extended the ‘erasure detection index’ (EDI) to detect fraudulent erasures at the group level. Sinharay (2018) suggested two modifications of the EDI at the group level. Those EDIs were not developed specifically for the fraudulent schools with small number of examinees with erasures. This paper suggested a new modification of the group-level EDI in Wollack and Eckerly (2017) by incorporating the ‘empirical best linear unbiased predictor’ (EBLUP) from the linear mixed-effects model. Simulation study shows that the suggested EDI has higher power than the indices of Wollack and Eckerly (2017) and Sinharay (2018), especially in schools with small number of examinees with erasures. It also has satisfactory Type I error rates. A real data example is also included.

